### ISSUE TITLE
插件启用后会导致公式编辑窗口很小，且无法调整

### ISSUE THREAD

**Issue by QMike0** [WingDr/siyuan-plugin-enhance-editor#1]
如题，该插件启用后似乎会固定公式编辑窗口的大小，并替换公式输入界面右下角的缩放按钮，导致无法拖动缩放窗口大小：
- 未启用本插件和插件「siyuan-math-enhance」，即思源原生公式编辑器：
  ![image](https://github.com/user-attachments/assets/4161d8a8-6f3d-4276-9dd8-8ab569af8571)
- 仅启用本插件：
  ![image](https://github.com/user-attachments/assets/fb1bc62e-44d0-4868-b043-450be0312617)
- 同时启用本插件和插件「siyuan-math-enhance」
  ![image](https://github.com/user-attachments/assets/c8772790-3e90-4f2a-9558-9ebaad4c118f)

另外，由于缩放按钮的替换，同时启用本插件和插件「siyuan-math-enhance」后，打开后者提供的数学虚拟按键就看不到缩放按钮了：
- 仅启用插件「siyuan-math-enhance」
  ![image](https://github.com/user-attachments/assets/ebcb3246-e819-4657-b483-8c4675f7ef91)
- 同时启用本插件和插件「siyuan-math-enhance」
  ![image](https://github.com/user-attachments/assets/79a8cc23-8c0c-4c98-b78b-e6ca20585a39)

**Comment by WingDr** [comment]
初始化的窗口小确实是个问题，主要是我不太清楚原本打开的时候窗口是多大的，目前是参考原本编辑器的最小宽度设定的（就是内容没撑开的时候初始化就是最小宽度）

无法缩放确实是个问题。右下角那个就是替换的原来的缩放按钮（原来那个是textarea原生的，但是div没有这种东西，只能自己搓一个），你看下鼠标移动到上面的时候会不会变成拉伸箭头的形状
![微信图片_20241028121032](https://github.com/user-attachments/assets/45f6d46b-7c96-4829-8699-480cdbc6c5ca)

另外可以用`ctr+shift+i`打开控制台看下有无报错，可能是没监听到对应元素

**Comment by WingDr** [comment]
拖动手柄的位置我再研究一下样式怎么写，最好是能够和原来保持一致

**Comment by WingDr** [comment]
我感觉我应该是定位到了问题，修改了一下并重新推送了，麻烦看下0.0.3版本有没有解决这个问题？

**Comment by QMike0** [comment]
谢谢佬的回复。
试了一下v 0.0.3版本，现在缩放按钮位置是正常的了，鼠标悬浮上去也会显示拉伸箭头，但还是无法实现拖动以缩放窗口
![image](https://github.com/user-attachments/assets/856b3ac8-324c-48e2-ac39-fbe69d5827ae)
控制台中对本插件的报错如下：
![image](https://github.com/user-attachments/assets/e25f84d9-a571-4e89-8335-20827f3c484a)

> 初始化的窗口小确实是个问题，主要是我不太清楚原本打开的时候窗口是多大的，目前是参考原本编辑器的最小宽度设定的（就是内容没撑开的时候初始化就是最小宽度）

测试了一下，思源原生公式编辑器的最小宽度（即使编辑器缩小到比这个宽度更窄）也要比本插件现有默认宽度更宽，目测大概在1.8倍左右，建议可以根据这个宽度调整一下本插件规定的默认宽度，不然感觉有点影响「siyuan-math-enhance」数字虚拟按键的使用
![image](https://github.com/user-attachments/assets/9b56cb14-3801-47c1-bb13-93e3dbb5bebb)

**Comment by WingDr** [comment]
> 控制台中对本插件的报错如下： ![image](https://private-user-images.githubusercontent.com/43239563/380608172-e25f84d9-a571-4e89-8335-20827f3c484a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTk1MTIsIm5iZiI6MTczMDA5OTIxMiwicGF0aCI6Ii80MzIzOTU2My8zODA2MDgxNzItZTI1Zjg0ZDktYTU3MS00ZTg5LTgzMzUtMjA4MjdmM2M0ODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA3MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NjJhNjE3MWZiOTM3NmVhZjQ1OTU0ZTE0YTA2ZmM3YzBjYzU0NjYzODBlNTUxNTdlZDI3OTg4NDQxYmY4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VG0zy4DV7-jFMP7Kcg5vzdRb-jDsu5Ij1Ey3sb9dk8g)

这个报错是math-enhance插件的报错，还有没有别的？或者最绝的方法，你用`ctrl+shift+i`打开控制台，然后控制台上面有个`元素`或者`element`的标签页点进去，再用最左上角的工具点一下，再点击编辑器角落那个小三角，下面应该会自动展开然后高亮这个元素对应的代码，点它。继续在右半边点击`事件监听器`，往下滑找到`mousedown`，点击展开，应该有一些`div.protyle-util`的东西，往下翻看看有没有像图里面这个`div`，然后后面是`loader.ts`的
![演示](https://github.com/user-attachments/assets/5fa922f6-bb85-4440-a09b-c4a23cfc0fd6)

上面说的点击小三角的时候应该是这样的
![选中小三角](https://github.com/user-attachments/assets/397bdcb6-ed86-4921-b6ff-b71d8d4fca85)

点击这个`loader.ts`之后应该是这样的代码
![image](https://github.com/user-attachments/assets/55a60680-eab0-4fae-beeb-ec9b9e800bff)

> 测试了一下，思源原生公式编辑器的最小宽度（即使编辑器缩小到比这个宽度更窄）也要比本插件现有默认宽度更宽，目测大概在1.8倍左右，建议可以根据这个宽度调整一下本插件规定的默认宽度，不然感觉有点影响「siyuan-math-enhance」数字虚拟按键的使用

这个我搞定了，初始化的时候直接同步原本textarea的宽度就行，就没那么麻烦了

**Comment by QMike0** [comment]
感谢手把手教学hhh

点击小三角的时候确实是显示如下参数：
![image](https://github.com/user-attachments/assets/1362f7ec-b036-4da5-8b68-1bcff089779f)
不过按照上述步骤操作后，并没有在`div`中找到`loader.ts`
![image](https://github.com/user-attachments/assets/83dc381d-da66-4bef-891d-20a16649533c)

> 控制台中对本插件的报错如下： image

这个报错是每次重新加载界面，即重新加载插件系统后都会立刻报出的

**Comment by WingDr** [comment]
> 不过按照上述步骤操作后，并没有在div中找到loader.ts

oh no，这个问题太致命了，监听事件根本没挂上。我尝试修复，另外想请你试试把图里这些插件逐个关掉，看看是不是它们的问题
![image](https://github.com/user-attachments/assets/4875eb24-f9b8-4451-adb1-16260ac20302)

**Comment by QMike0** [comment]
尝试只开本插件，出现了很神奇的现象。如图，`div`中依然没有`loader.ts`：
![image](https://github.com/user-attachments/assets/8b431d2c-bc2f-4c86-908d-a03a883e7421)
但是此时小三角时可以拖动以缩放公式编辑窗口大小的

> 另外想请你试试把图里这些插件逐个关掉，看看是不是它们的问题

经过排查，似乎是与插件[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)存在冲突，启用该插件后，就会导致本插件公式编辑界面的小三角失效
_注：不过即使关闭该插件，`div`中依然没有`loader.ts`_

**Comment by WingDr** [comment]
> 经过排查，似乎是与插件[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)存在冲突，启用该插件后，就会导致本插件公式编辑界面的小三角失效
注：不过即使关闭该插件，div中依然没有loader.ts

关闭这个插件之后不一定会触发，要刷新一下思源（或者直接关掉再开启思源），然后再看看loader.ts有没有挂载上

**Comment by WingDr** [comment]
> 经过排查，似乎是与插件[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)存在冲突，启用该插件后，就会导致本插件公式编辑界面的小三角失效
注：不过即使关闭该插件，div中依然没有loader.ts

关闭这个插件之后不一定会触发，要刷新一下思源（或者直接关掉再开启思源），然后再看看loader.ts有没有挂载上

**Comment by QMike0** [comment]
> 关闭这个插件之后不一定会触发，要刷新一下思源（或者直接关掉再开启思源），然后再看看loader.ts有没有挂载上

嗯嗯，已经尝试了
1. 只开本插件，关闭重启思源
2. 单独关闭插件[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)而启动其他插件，关闭重启思源

得到的`div`都是没有`loader.ts`的，但小三角的拖动生效

**Comment by WingDr** [comment]
> 嗯嗯，已经尝试了
> 
> 1. 只开本插件，关闭重启思源
> 2. 单独关闭插件[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)而启动其他插件，关闭重启思源
> 
> 得到的`div`都是没有`loader.ts`的，但小三角的拖动生效

小三角的拖动生效就说明没问题，这个[Misuzu](https://github.com/Misuzu2027/syplugin-misuzu-custom)有什么比较重要的功能吗？他的代码我研究不明白orz

**Comment by QMike0** [comment]
![image](https://github.com/user-attachments/assets/8df732c2-4e46-4161-bdf1-9708e321fd0a)
![image](https://github.com/user-attachments/assets/e7d36033-fdda-405f-9482-e2c4fd14fc39)

主要在用它的这个功能，代码块填写语言类型的时候会方便一些

冲突的话，我打算先把它关闭了hh，用的时候再开

**Comment by QMike0** [comment]
佬辛苦了哈，修了一下午bug hhhh

**Comment by WingDr** [comment]
> ![image](https://private-user-images.githubusercontent.com/43239563/380646200-8df732c2-4e46-4161-bdf1-9708e321fd0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDc4NzYsIm5iZiI6MTczMDEwNzU3NiwicGF0aCI6Ii80MzIzOTU2My8zODA2NDYyMDAtOGRmNzMyYzItNGU0Ni00MTYxLWJkZjEtOTcwOGUzMjFmZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNWZkZWY3ZmNlMDNiMTUyNzg4YzY3MmU1Yjg3ZGNhMGJjYTYwMjg1MjhkYTQ1ZmRmMTdhOGI4OGY1MjVkNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OJahmTrcPOmjcFhl4QlQ1Odu_hZ3Rk5D0QZmCCcatmc) ![image](https://private-user-images.githubusercontent.com/43239563/380647374-e7d36033-fdda-405f-9482-e2c4fd14fc39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDc4NzYsIm5iZiI6MTczMDEwNzU3NiwicGF0aCI6Ii80MzIzOTU2My8zODA2NDczNzQtZTdkMzYwMzMtZmRkYS00MDVmLTk0ODItZTJjNGZkMTRmYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNWExYzEwYTJhODJjZTY2ZDI2ODBlNDA5MGRkNjRjZWU3Zjg1ZWY0Zjg5ZWE0NDk2YTMyMjQzMmFkZWVlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._oML4a-CtzqypPsr71mvW7lgkqkRCGwYpLc-MCizAWU)
> 
> 主要在用它的这个功能，代码块填写语言类型的时候会方便一些
> 
> 冲突的话，我打算先把它关闭了hh，用的时候再开

okk，我在readme里注明一下，我简单看了一下，大概是被他的一个全局的鼠标事件触发拦截了，可能那边有些特殊需求吧

**Comment by WingDr** [comment]
> 佬辛苦了哈，修了一下午bug hhhh

没事，我也在de其他的bug，甚至顺带去修改了一下math-enhance插件的东西，待会儿去提pull request hhh

**Comment by QMike0** [comment]
> 没事，我也在de其他的bug，甚至顺带去修改了一下math-enhance插件的东西，待会儿去提pull request hhh

牛蛙
