### ISSUE TITLE
自动补全产生多余花括号

### ISSUE THREAD

**Issue by ShawElA** [WingDr/siyuan-plugin-enhance-editor#2]
在使用自动补全功能时，有时会出现多余的花括号。

例如：预期输入结果为 `\begin{cases} \end{cases}`，而在键入 `\begin{c}` 并使用自动补全后，生成的结果包含多余的右花括号，即 `\begin{cases} \end{cases}}`。

虽然可以通过键入 `\beginca` 来避免，但打花括号打顺手了还是挺容易出问题，希望能优化自动补全逻辑。

**Comment by WingDr** [comment]
哦，这个是因为自动合并括号产生的问题，我尝试改一下补全的正则应该就行

**Comment by WingDr** [comment]
加了个判断，检测到补全里面有大括号就自动把后面一个字符一起替换，只要不乱输入应该就没问题，等新版本推送就好了
