### ISSUE TITLE
优化公式块的退出响应和光标定位

### ISSUE THREAD

**Issue by ShawElA** [WingDr/siyuan-plugin-enhance-editor#3]
1. 思源的逻辑：

    * 行级公式块：敲击“ESC”即可关闭，并将光标定位在公式块右侧，无论前面是否有文字。
    * 公式块：敲击“ESC”两次（第一次敲击后退出公式块并选中公式块）并按一次回车即可退出并换行。
2. 开启插件后：

    * 行级公式块：需多敲击“ESC”两次来关闭公式。如果行级公式块前没有文字，光标会被定位在公式块左侧。
    * 公式块：需额外敲击一次回车来换行（第一次敲击“ESC”后没有关闭公式块窗口）。

https://github.com/user-attachments/assets/9b8880ea-3679-41f9-a18e-b5ec7a84f880

**Comment by ShawElA** [comment]
公式块和思源不一样感觉也行，思源公式块敲一次“ESC”后默认选中也挺难受的

**Comment by WingDr** [comment]
我现在把这些键还原成思源本身的触发逻辑了，主要是之前快捷键这里一直没搞好，等目前的问题都解决了就推新版本
