### ISSUE TITLE
优化分屏输入

### ISSUE THREAD

**Issue by ShawElA** [WingDr/siyuan-plugin-enhance-editor#5]
在两个分屏同时打开公式块并分别输入内容会出现显示混乱

**Comment by WingDr** [comment]
是什么混乱呢？我这试了一下没问题啊

**Comment by ShawElA** [comment]
https://github.com/user-attachments/assets/e165f6ef-6404-4bfd-aa16-f330266665a8

不知道怎么描述，看下视频吧
