### ISSUE TITLE
错误补全双参数命令的简写形式

### ISSUE THREAD

**Issue by ShawElA** [WingDr/siyuan-plugin-enhance-editor#9]
双参数命令（如`\frac{}{}`）以简写形式（如`\frac12`）作为其他命令的参数时，插件错误将简写形式视为单参数命令，导致错误补全。

如：`\boxed{\frac12}`被补全为`\boxed{\frac{12}}`。

https://github.com/user-attachments/assets/7e06f11a-bf52-498a-9f22-7549907115ca

**Comment by WingDr** [comment]
这个没办法，用的自动排版是[prettier latex](https://github.com/siefkenj/prettier-plugin-latex)，我试了一下他确实会有这个问题。但是我觉得自动排版利大于弊，这个也不是什么特别难受的bug，所以就这样吧orz

或者可以选择向prettier latex提issue，那边要是改了我可以第一时间更新
